/*
 * generated by Xtext
 */
package fr.uns.i3s.rainbow.captah.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CaPtahRuntimeModule extends fr.uns.i3s.rainbow.captah.dsl.AbstractCaPtahRuntimeModule {

}
