/*
* generated by Xtext
*/
package fr.uns.i3s.rainbow.captah.dsl.ui.contentassist;

import fr.uns.i3s.rainbow.captah.dsl.ui.contentassist.AbstractCaPtahProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class CaPtahProposalProvider extends AbstractCaPtahProposalProvider {

}
