/*
 * generated by Xtext
 */
package fr.uns.i3s.rainbow.captah.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CaPtahUiModule extends fr.uns.i3s.rainbow.captah.dsl.ui.AbstractCaPtahUiModule {
	public CaPtahUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
